name: Backend Workflow

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore project dependencies
        run: dotnet restore backend/Api/Api.csproj
      - name: Run Unit Tests
        run: dotnet test backend/Api.Test/Api.Test.csproj
      - name: Run Integration Tests
        run: dotnet test backend/Api.IntegrationTest/Api.IntegrationTest.csproj